In [5]:
import numpy as np 

In [6]:
class Player(object):
    def __init__(self,name):
        self.name=name
        self.table = np.zeros((7,7))
        self.tableAtk = np.zeros((7,7))
    
    def getName(self):
        return self.name
    
    def getTab(self):
        return self.table
    
    def getTabAtk(self):
        return self.tableAtk
    
    def getPos(self,posx,posy):
        a = int(self.table[posx,posy])
        return a
    
    def setTab(self,pos):
        self.table[pos]=1
        
    def setTabAtk(self,pos,a):
        if a == 1:
            self.tableAtk[pos]=4
        else:
            self.tableAtk[pos]=8
        
    def setTabX(self,pos,a):
        if a == 1:
            self.table[pos]=4
        else:
            self.table[pos]=8
        
        
    def getCon(self):
        b = len(self.table[self.table == 1])
        return b
        
 

In [12]:
def ori():
    print("****orientation****")
    
    ori={1:"UP",2:"DOWN",3:"LEFT",4:"RIGHT"}
    
    for i in ori.items():
        print (i[0], " ", i[1])
    a= input()
    
    if  a.isdigit():
        b=int(a)
        
        if b in ori:
            return b
        else:
            print("Invalid")
            ori()
    else:
        print("Invalid")
        ori()
        
        
def putB(obj, b, o, cx,cy):
    lb=len(b)
    if lb>1:
       
        if o == 1:
            if ((cx+1) < lb):
                print("your boat does not fit in this position")
            else:
                
                for i in range(lb):
                    obj.setTab((cx,cy))
                    cx-=1
                    
               
                
                
        elif (o == 2):
            if ((7-cx) < lb):
                print("your boat does not fit in this position")
            else:
                
                for i in range(lb):
                    obj.setTab((cx,cy))
                    cx+=1
                    
                
        elif (o == 3):
            if ((cy+1) < lb):
                print("your boat does not fit in this position")
            else:
                
                for i in range(lb):
                    obj.setTab((cx,cy))
                    cy-=1
                    
               
        else:
            if ((7-cy) < lb):
                print("your boat does not fit in this position")
            else:
                
                for i in range(lb):
                    obj.setTab((cx,cy))
                    cy+=1
                    
               
    else:
        obj.setTab((cx,cy))
        
        
def abst(s, b, o):
    print(f"{s}")
    print(b)
    print("In what coordinates do you want to place it?")
    print("start at y ")
    ix=int(input())
    print("start at x")
    iy=int(input())
    a = ori()
    putB(o,b,a,ix,iy)
        
        
def board(obj):
    b1= np.ones((4))
    b2= np.ones((3))
    b3= np.ones((2))
    b4= np.ones((1))
    b=4
    print(f"{obj.getName()} You have {b} boats")
    print(" This is your board")
    print(obj.getTab())
    abst('First Boat',b1,obj)
    abst('Second Boat',b2,obj)
    abst('Third Boat',b3,obj)
    abst('Fourth Boat',b4,obj)
    

    
def victory(obj):
    a = obj.getCon()
    
    if a == 0:
        return 1
    else:
        return 0

def atk(obj1, obj2):
      
    print(" This is your board")
    print(obj1.getTab())
    print(" This is your board attack")
    print(obj1.getTabAtk())
    
    print(f"{obj1.getName()} What position do you want to attack?")
    print(" y ")
    ax=int(input())
    print(" x ")
    ay=int(input())
    a= obj2.getPos(ax,ay)
    obj2.setTabX((ax,ay),a)
    obj1.setTabAtk((ax,ay),a)
    
    
    if a == 1:
        
        print (f"{obj1.getName()}: IMPACT")
        c = victory(obj2)
        if c == 1:
            print (f"{obj1.getName()}: YOU WIN")
            print(f"{obj1.getName()} This is your board")
            print(obj1.getTab())
            print(f"{obj2.getName()} This is your board")
            print(obj2.getTab())
        else:
            return 1
    
    else:
       
        return 0
        
    
    

    
def game(obj1,obj2,t1,t2):
    pt1=t1
    pt2=t2
    
    
    
    if (pt1 == 1):
        a = atk(obj1,obj2)
        if a == 1:
            t1 = 1
            t2 = 0
            game(obj1,obj2,t1,t2)
        elif a == 0:
            t1 = 0
            t2 = 1
            game(obj1,obj2,t1,t2)
        else:
            print("END GAME")
    else:
        a = atk(obj2,obj1)
        if a == 1:
            t2 = 1
            t1 = 0
            game(obj1,obj2,t1,t2)
        elif a == 0:
            t2 = 0
            t1 = 1
            game(obj1,obj2,t1,t2)
        else:
            print("END GAME")
            
           
    
        

def ini():
    print("Player 1, what's your name?")
    p1=Player(input())
    print("Player 2, what's your name?")
    p2=Player(input())
    
    board(p1)
    print(p1.getTab())
    board(p2)
    print(p1.getTab())
    game(p1,p2,1,0)

In [11]:
ini()

Player 1, what's your name?
w
Player 2, what's your name?
q
w You have 4 boats
 This is your board
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
First Boat
[1. 1. 1. 1.]
In what coordinates do you want to place it?
start at y 
4
start at x
0
****orientation****
1   UP
2   DOWN
3   LEFT
4   RIGHT
1
Second Boat
[1. 1. 1.]
In what coordinates do you want to place it?
start at y 
4
start at x
1
****orientation****
1   UP
2   DOWN
3   LEFT
4   RIGHT
1
Third Boat
[1. 1.]
In what coordinates do you want to place it?
start at y 
4
start at x
2
****orientation****
1   UP
2   DOWN
3   LEFT
4   RIGHT
1
Fourth Boat
[1.]
In what coordinates do you want to place it?
start at y 
4
start at x
3
****orientation****
1   UP
2   DOWN
3   LEFT
4   RIGHT
1
[[0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0